server:
  port: 8080
 
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    url: jdbc:db2://192.168.211.128:50000/KRDB
    username: mrndbuser
    password: pwMujH9h3dD0

    hikari:
      minimum-idle: 5
      #连接池中允许的最大连接数。缺省值：10
      maximum-pool-size: 20
      auto-commit: true
      #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000